apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: prometheus
  namespace: prometheus
spec:
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 9090
    nodePort: 30909
  selector:
    app: prometheus
  type: NodePort
status:
  loadBalancer: {}
