apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
  name: px-repl2-sc-volexp
parameters:
  io_profile: db_remote
  repl: "2"
provisioner: pxd.portworx.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
---
apiVersion: v1
kind: Namespace
metadata:
  name: autogrow
  labels: 
    type: growtest
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: autogrow
  namespace: autogrow
spec:
  storageClassName: px-repl2-sc-volexp
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: grower
  name: grower
  namespace: autogrow
spec:
  volumes:
    - name: growvol
      persistentVolumeClaim:
        claimName: autogrow
  containers:
  - image: docker.io/jacint/grower
    name: grower
    volumeMounts:
        - mountPath: "/mnt"
          name: growvol
  dnsPolicy: ClusterFirst
  restartPolicy: Always
