apiVersion: v1
kind: Namespace
metadata:
  name: autogrow
  labels: 
    type: growtest
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: autogrow
  namespace: autogrow
spec:
  storageClassName: px-repl2-sc-ag
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: grower
  name: grower
  namespace: autogrow
spec:
  volumes:
    - name: growvol
      persistentVolumeClaim:
        claimName: autogrow
  containers:
  - image: docker.io/jacint/grower
    name: grower
    volumeMounts:
        - mountPath: "/mnt"
          name: growvol
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
