apiVersion: v1
kind: Namespace
metadata:
  name: autogrow
  labels:
    type: autogrow
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: autogrow
  namespace: autogrow
spec:
  storageClassName: px-csi-db
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: grower
  name: grower
  namespace: autogrow
spec:
  volumes:
    - name: growvol
      persistentVolumeClaim:
        claimName: autogrow
  containers:
    - env:
        - name: DEBUG
          value: "yes"
      image: docker.io/jacint/grower
      name: grower
      volumeMounts:
        - mountPath: "/mnt"
          name: growvol
  dnsPolicy: ClusterFirst
  restartPolicy: Always
