apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
  name: px-repl2-sc-ag
parameters:
  io_profile: db_remote
  repl: "2"
provisioner: pxd.portworx.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true

