kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: grafana-pvc
  namespace: grafana
spec:
  storageClassName: px-repl2-sc-volexp
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

