apiVersion: v1
kind: Pod
metadata:
  name: nginx-pv
spec:
  containers:
  - name: nginx-pv
    image: nginx
    volumeMounts:
    - name: varwww
      mountPath: /var/www
  volumes:
  - name: varwww
    persistentVolumeClaim:
      claimName: px-rwo-pvc

