apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvc
  namespace: csitest
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: px-fb-direct-access-nfsv3
  resources:
    requests:
      storage: 500Mi

