apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvc
  namespace: csitest
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: px-fa-direct-access
  resources:
    requests:
      storage: 500Mi

